version: "3.8"

services:
  db:
    container_name: newsletter_db
    environment:
      - PG_DATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=newsletter
      - POSTGRES_PASSWORD=iUFXkPr7_!nm98EY
      - POSTGRES_USER=postgres
    healthcheck:
      interval: 20s
      retries: 3
      start_period: 10s
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      timeout: 5s
    image: postgres:15
    networks:
      newsletter_net:
        aliases:
          - newsletter_db
    ports:
      - "5432:5432"
    volumes:
      - newsletter_db:/var/lib/postgresql/data

networks:
  newsletter_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.20.20.0/24
    name: newsletter_net

volumes:
  newsletter_db:
    name: newsletter_db
